version: 1

services:
  # 後端 API 服務 (Express)
  - type: web
    name: tcrs-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ALLOWED_ORIGINS
        # 部署後填入前端正式網址 (例: https://tcrs-web.onrender.com)
        value: https://你的前端網址
    autoDeploy: true
    healthCheckPath: /api/health

  # 前端 Web 服務 (使用 serve 提供 dist)
  - type: web
    name: tcrs-web
    env: node
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build && npm install -D serve
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_BASE
        value: https://你的API網址/api
    autoDeploy: true
